### PR TITLE
Show data provider details in slow test list

### LINKED ISSUE #553: Values from data provider are not shown for slow test
#### Steps required to reproduce the problem

Basically the same as https://github.com/sebastianbergmann/phpunit/issues/5616 but for this extension. Something like https://github.com/sebastianbergmann/phpunit/commit/5d049893b805733369a72dab5b92556a1f665eb9#diff-0185eeda9f2d10b7587e9a551c2658419c534b49fa2a6dfe0dc0a72d294557ceR522 is needed.

I would expected the data provider values to be shown the same way as phpunit list failed tests. This is actually working for PHPUnit 9.x and lower already.

#### Expected Result

(from phpunit 9.x)

```
Detected 4 tests where the duration exceeded the maximum duration.

1. 6.049 (0.500) Atk4\Data\Tests\ConditionSqlTest::testLikeCondition with data set #1 ('binary', true)
2. 6.041 (0.500) Atk4\Data\Tests\ConditionSqlTest::testLikeCondition with data set #2 ('text', false)
3. 5.897 (0.500) Atk4\Data\Tests\ConditionSqlTest::testLikeCondition with data set #3 ('blob', true)
4. 5.861 (0.500) Atk4\Data\Tests\ConditionSqlTest::testLikeCondition with data set #0 ('string', false)
```

#### Actual Result

(from phpunit 11.x, ignore different tests listed)

```
Detected 5 tests where the duration exceeded the maximum duration.

1. 3.128 (0.500) Atk4\Data\Tests\ScopeTest::testConditionOnReferencedRecords
2. 0.999 (0.500) Atk4\Data\Tests\ConditionSqlTest::testRegexpCondition#0
3. 0.968 (0.500) Atk4\Data\Tests\ConditionSqlTest::testRegexpCondition#3
4. 0.967 (0.500) Atk4\Data\Tests\ConditionSqlTest::testRegexpCondition#2
5. 0.953 (0.500) Atk4\Data\Tests\ConditionSqlTest::testRegexpCondition#1
```

### PR DESCRIPTION
**Pull request by mvorisek**
fix #553

Show data provider data the same way how PHPUnit default formatter report them.

In PHPUnit v9 and below this is already done.

### CODE REVIEW

**Comment by mvorisek** [comment]
@localheinz can I ask you to review and help me fixing the CI as the code is not analyseable by PHP 7.4, as PHPUnit 10+ is not for PHP 7.4.

**Comment by localheinz** [comment]
@mvorisek 

I will take a look on the weekend!

**Comment by mvorisek** [comment]
> I will take a look on the weekend!

@localheinz I would really appreciate this PR to be merged :)

**Comment by mvorisek** [comment]
@localheinz a month ago, you promised to look at this PR "on the weekend" - I know everyone is busy with somethings, but would you mind to look into the CI now? Thank you in advance!

**Comment by mvorisek** [comment]
@localheinz a month ago, you promised to look at this PR "on the weekend" - I know everyone is busy with somethings, but would you mind to look into the CI now? Thank you in advance!

**Comment by localheinz** [comment]
Taking a look now, @mvorisek!

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @mvorisek!

**Comment by mvorisek** [comment]
@localheinz Thank you ❤

**Pull request merged**
