### PR TITLE
Consistently include test setup and teardown in duration measurement

### LINKED ISSUE #378: Measured time must include test setup/teardown
Currently the measured time does not include test teardown.

The solution is to drop
https://github.com/ergebnis/phpunit-slow-test-detector/blob/2.4.0/src/Subscriber/TestPassedSubscriber.php
as it is called in
https://github.com/sebastianbergmann/phpunit/blob/10.4.2/src/Framework/TestCase.php#L723
and use
https://github.com/sebastianbergmann/phpunit/blob/10.4.2/src/Framework/TestRunner.php#L238
"test finished" hook solely instead.

In "test finished" hook `TestCase->status()->isFailure() && TestCase->status()->isError()` can be used to filter out non-passing tests, but probably even non-passing tests can/should be reported if slow.

### PR DESCRIPTION
**Pull request by mvorisek**
fix #378, measure the whole `TestCase::runBare()` duration

also measure any test, not only the successful ones, measuring failed/errored tests is helpful especially for tests using IO or external services

### CODE REVIEW

**Comment by mvorisek** [comment]
Please, let's merge this PR too.

**Comment by localheinz** [comment]
@mvorisek 

Two things:

- I do not believe this extension should report slow tests that have not passed. When I have a test suite where a test has not passed, I would fix the failing test first, and improve the speed of passing tests second.
- If we want to (somewhat) consistently report slow tests across `phpunit/phpunit:^8.5.19`, `phpunit/phpunit:^9.0.0`, and `phpunit/phpunit:^10.0.0`, then the extension should probably 
    - start timing on [`PHPUnit\Event\Test\BeforeFirstTestMethodCalled`](https://github.com/sebastianbergmann/phpunit/blob/10.0.0/src/Event/Events/Test/HookMethod/BeforeFirstTestMethodCalled.php)
    - stop timing on [`PHPUnit\Event\Test\AfterTestMethodFinished `](https://github.com/sebastianbergmann/phpunit/blob/10.0.0/src/Event/Events/Test/HookMethod/AfterTestMethodFinished.php)

What do you think?

**Comment by mvorisek** [comment]
> I do not believe this extension should report slow tests that have not passed. When I have a test suite where a test has not passed, I would fix the failing test first, and improve the speed of passing tests second.

I belive it should. When failed test failed fast, it is never reported. And in general, tests do not fail slower than when passed fully.

But if a failed test took longer than a maximum duration, it should be reported to make the developer aware there is also some slowness issue. Especially when run remotely/in CI.

> If we want to (somewhat) consistently report slow tests across `phpunit/phpunit:^8.5.19`, `phpunit/phpunit:^9.0.0`, and `phpunit/phpunit:^10.0.0`, then the extension should probably

I am looking into the PHPUnit v8/9 hooks to make the behaviour consistent.

**Comment by mvorisek** [comment]
@localheinz sorry for a lot of force pushed, now everything is fixed and tests are passing.

**Comment by mvorisek** [comment]
@localheinz I have rebased this PR on the latest main, may I ask you to look into it and tag a new release?

**Comment by mvorisek** [comment]
Time measurement differences across PHPUnit versions are now fixed/consistent.

**Comment by mvorisek** [comment]
Rebased.

**Comment by localheinz** [comment]
@mvorisek 

Don't worry about rebasing, I'm working on it and will finish it in a moment!

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @mvorisek!

**Pull request merged**
